pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'Compiling source code...'
                sh 'make -C main'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Running tests...'
                sh './main/hello_exec'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'echo "Deployment step placeholder"'
            }
        }
    }
    
    post {
        failure {
            echo 'pipeline failed'
        }
    }
}
